# Generated by Django 3.1 on 2020-08-31 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200831_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='institution',
            name='additional_info',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='institution',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='institution',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
